[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "protocol_identifier"
version = "0.0.1"
requires-python = ">=3.10"
readme = "README.md"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests", "scripts"]